apiVersion: v1
kind: Secret
metadata:
  name: mir-api
type: Opaque
## Usage of 'stringData' field rather than 'data' to leverage automatic base64 en-/decoding 
## (ref. https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually)
stringData:
  mirhost: "{{ .Values.envs.mirhost }}"
  miruser: "{{ .Values.envs.miruser }}"
  mirpswd: "{{ .Values.envs.mirpassword }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mir-travel-time-calculator-{{ .Values.robot.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mir-travel-time-calculator-{{ .Values.robot.name }}
  template:
    metadata:
      labels:
        app: mir-travel-time-calculator-{{ .Values.robot.name }}
    spec:
      containers:
      - name: mir-travel-time-calculator
        image: {{ .Values.image }}
        env:
        - name: MIR_USER
          valueFrom:
            secretKeyRef:
              name: mir-api
              key: miruser
        - name: MIR_HOST
          valueFrom:
            secretKeyRef:
              name: mir-api
              key: mirhost
        - name: MIR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mir-api
              key: mirpswd
        - name: ROBCO_ROBOT_NAME
          value: "{{ .Values.robot.name }}"
        - name: MIR_HTTP_TIMEOUT
          value: "{{ .Values.envs.mirhttptimeout }}"
        - name: MIR_PERSERVE_PATHGUIDES
          value: "{{ .Values.envs.mirpreservepathguides }}"
        - name: PRECALC_PATHS_WHEN_IDLE
          value: "{{ .Values.envs.precalcpathswhenidle }}"
        - name: MIR_FLEET_CONFIG
          value: "{{ .Values.envs.mirfleetconfig }}"
        - name: LOG_LEVEL
          value: {{ .Values.envs.log.level }}
        - name: LOG_FORMAT
          value: {{ .Values.envs.log.format }}
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "250m"
