apiVersion: v1
kind: Secret
metadata:
  name: mir-api
type: Opaque
## Usage of 'stringData' field rather than 'data' to leverage automatic base64 en-/decoding 
## (ref. https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually)
stringData:
  mirhost: "{{ .Values.envs.mirhost }}"
  miruser: "{{ .Values.envs.miruser }}"
  mirpswd: "{{ .Values.envs.mirpassword }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mir-mission-controller-{{ .Values.robot.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mir-mission-controller-{{ .Values.robot.name }}
  template:
    metadata:
      labels:
        app: mir-mission-controller-{{ .Values.robot.name }}
    spec:
      containers:
      - name: mir-mission-controller
        image: {{ .Values.image.repository }}{{ if .Values.image.tag }}:{{ .Values.image.tag }}{{ end }}
        imagePullPolicy: Always
        env:
        - name: MIR_USER
          valueFrom:
            secretKeyRef:
              name: mir-api
              key: miruser
        - name: MIR_HOST
          valueFrom:
            secretKeyRef:
              name: mir-api
              key: mirhost
        - name: MIR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mir-api
              key: mirpswd
        - name: ROBCO_ROBOT_NAME
          value: "{{ .Values.robot.name }}"
        - name: PLC_TROLLEY_ATTACHED
          value: "{{ .Values.envs.plctrolley }}"
        - name: AUTO_RESET_ERRORS
          value: "{{ .Values.envs.autoreseterrors }}"
---
apiVersion: v1
kind: Service
metadata:
  name: mir-mission-controller-{{ .Values.robot.name }}
  labels:
    app: mir-mission-controller-{{ .Values.robot.name }}
spec:
  ports:
  - name: metrics
    port: 8000
  selector:
    app: mir-mission-controller-{{ .Values.robot.name }}
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mir-mission-controller-{{ .Values.robot.name }}
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: mir-mission-controller-{{ .Values.robot.name }}
