image: "ewmcloudrobotics/mir-travel-time-calculator"

tenant_main_namespace: "default"

envs:
  miruser: "admin"
  mirpassword: ""
  mirhost: "mir-api.default.svc.cluster.local"
  mirhttptimeout: "60"
  mirfleetconfig: ""
  log: 
    format: "json"
    level: "info"
