apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # annotation has to be provided in order to enable cr-syncer to cloud
  annotations:
    cr-syncer.cloudrobotics.com/spec-source: cloud
    cr-syncer.cloudrobotics.com/filter-by-robot-name: "True"
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: warehouseorders.ewm.sap.com
spec:
  # list of versions supported by this CustomResourceDefinition
  group: ewm.sap.com
  # list of versions supported by this CustomResourceDefinition
  version: v1alpha1
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  subresources:
    status: {}
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: warehouseorders
    # singular name to be used as an alias on the CLI and for display
    singular: warehouseorder
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: WarehouseOrder
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ord
  validation:
    openAPIV3Schema:
      type: object
      required:
        - spec
      properties:
        spec:
          type: object
          required:
            - data
            - order_status
          properties:
            data:
              type: object
              required:
                - lgnum
                - who
                - status
                - areawho
                - lgtyp
                - lgpla
                - queue
                - rsrc
                - lsd
                - topwhoid
                - refwhoid
                - flgwho
                - flgto
                - warehousetasks
              properties:
                lgnum:
                  type: string
                who:
                  type: string
                status:
                  type: string
                areawho:
                  type: string
                lgtyp:
                  type: string
                lgpla:
                  type: string
                queue:
                  type: string
                rsrc:
                  type: string
                lsd:
                  type: integer
                topwhoid:
                  type: string
                refwhoid:
                  type: string
                flgwho:
                  type: boolean
                flgto:
                  type: boolean
                warehousetasks:
                  type: array
                  items:
                    type: object
                    required: 
                      - flghuto
                      - lgnum
                      - meins
                      - nlber
                      - nlenr
                      - nlpla
                      - nltyp
                      - priority
                      - tanum
                      - tostat
                      - unitv
                      - unitw
                      - vlber
                      - vlenr
                      - vlpla
                      - vltyp
                      - volum
                      - vsolm
                      - weight
                      - who
                    properties:
                      flghuto:
                        type: boolean
                      lgnum:
                        type: string
                      meins:
                        type: string
                      nlber:
                        type: string
                      nlenr:
                        type: string
                      nlpla:
                        type: string
                      nltyp:
                        type: string
                      priority:
                        type: integer
                      tanum:
                        type: string
                      tostat:
                        type: string
                      unitv:
                        type: string
                      unitw:
                        type: string
                      vlber:
                        type: string
                      vlenr:
                        type: string
                      vlpla:
                        type: string
                      vltyp:
                        type: string
                      volum:
                        type: integer
                      vsolm:
                        type: integer
                      weight:
                        type: integer
                      who:
                        type: string
            process_status:
              type: array
              items:
                type: object
                required:
                  - confirmationdate
                  - confirmationnumber
                  - confirmationtype
                  - lgnum
                  - rsrc
                  - tanum
                  - who
                properties:
                  confirmationdate:
                    type: string
                  confirmationnumber:
                    type: string
                  confirmationtype:
                    type: string
                  lgnum:
                    type: string
                  rsrc:
                    type: string
                  tanum:
                    type: string
                  who:
                    type: string
            order_status:
              type: string
              enum:
                - RUNNING
                - PROCESSED
        status:
          type: object
          properties:
            data:
              type: array
              items:
                type: object
                required:
                  - confirmationdate
                  - confirmationnumber
                  - confirmationtype
                  - lgnum
                  - rsrc
                  - tanum
                  - who
                properties:
                  confirmationdate:
                    type: string
                  confirmationnumber:
                    type: string
                  confirmationtype:
                    type: string
                  lgnum:
                    type: string
                  rsrc:
                    type: string
                  tanum:
                    type: string
                  who:
                    type: string
  additionalPrinterColumns:
  - JSONPath: .spec.data.lgnum
    name: EWM Warehouse
    type: string
  - JSONPath: .spec.data.rsrc
    name: EWM Robot
    type: string
  - JSONPath: .spec.order_status
    name: Order Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
