apiVersion: v2
description: Basic mission controller confirming every mission CRD
name: dummy-mission-controller
version: 0.0.1
dependencies:
- name: mission-crd
  version: "0.0.1"
  repository: "file://../dependency-charts/mission-crd"
  condition: missioncrd.enabled