---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dummy-mission-controller-{{ .Values.robot.name }}
spec:
  replicas: 1
  serviceName: dummy-mission-controller-{{ .Values.robot.name }}
  selector:
    matchLabels:
      app: dummy-mission-controller-{{ .Values.robot.name }}
  template:
    metadata:
      labels:
        app: dummy-mission-controller-{{ .Values.robot.name }}
    spec:
      containers:
      - name: dummy-mission-controller-{{ .Values.robot.name }}
        image: {{ $.Values.image }}
        env:
        - name: ROBCO_ROBOT_NAME
          value: "{{ .Values.robot.name }}"
        - name: LOG_LEVEL
          value: {{ $.Values.envs.log.level }}
        - name: LOG_FORMAT
          value: {{ $.Values.envs.log.format }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "250m"
