apiVersion: v1
kind: ConfigMap
metadata:
  name: app-auth-proxy
  labels:
    app: app-auth-proxy
data:
  config.json: |
    {
      "routes": [{
              "path": "{{ $.Values.nginxpath }}",
              "priority": 10,
              "protected": true,
              "remove_from_path": "{{ $.Values.nginxpath }}",
              "target": "http://monitoring-ui:80",
              "forward_auth_token": false,
              "http_method_scopes": [{
                "http_method": "*",
                "scope": "*"
            }]
          }],
      "token_endpoint_auth_method": "client_secret_post",
      "redirect_uri": "https://monitoring-ui.{{ .Values.tenant_domain }}/oauth/callback",
      "debug": false,
      "redis_store": {
        "addr": "",
        "password": "",
        "db": 0
      },
      "cookie":{
          "session_name": "monitoring-ui-{{ .Values.tenant }}-session",
          "max_age_seconds": 900,
          "key": "{{ .Values.cookie_secret }}",
          "httponly": true
      }
    }
