apiVersion: v1
appVersion: "1.0"
description: SAP EWM Robot Controller Extension for Robco Platform
name: ewm-robot-controller
version: 0.0.1
                                                               