apiVersion: v2
description: Mission controller for Fetch robots
name: fetch-mission-controller
version: 0.0.1
dependencies:
- name: mission-crd
  version: "0.0.1"
  repository: "file://../dependency-charts/mission-crd"
  condition: missioncrd.enabled