apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-robotics:mission-controller
rules:
- apiGroups:
  - registry.cloudrobotics.com
  resources:
  - robots
  - robots/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mission.cloudrobotics.com
  resources:
  - missions
  - missions/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registry.cloudrobotics.com
  resources:
  - robots/status
  verbs:
  - update
  - patch
- apiGroups:
  - mission.cloudrobotics.com
  resources:
  - missions/status
  verbs:
  - update
  - patch
