replicaCount: 1
image:
  repository: "ewmcloudrobotics/mir-mission-controller"
  tag: "latest"

envs:
  plctrolley: 5
  miruser: "admin"
  mirpassword: ""
  mirhost: "mir-api.default.svc.cluster.local"
  autoreseterrors: "false"

robot:
  name: ""